UnitTestBot/ksmt

ksmt-bitwuzla/build.gradle.kts
ksmt-z3/build.gradle.kts

Currently, `JitPack` fails to build KSMT because of issues with z3 release download.
Build fails if gradle `clean` and `build` tasks are executed in a single command, because gradle doesn't redownload `z3-release`.

Fix z3 build

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaSolver.kt
ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/ConverterTest.kt
ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/Example.kt
ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/SolverTest.kt
ksmt-core/src/main/kotlin/example/Example.kt
ksmt-core/src/main/kotlin/example/Transformer.kt
ksmt-core/src/main/kotlin/org/ksmt/KContext.kt
ksmt-core/src/main/kotlin/org/ksmt/solver/model/KModelEvaluator.kt
ksmt-core/src/main/kotlin/org/ksmt/utils/ContextUtils.kt
ksmt-runner/src/test/kotlin/org/ksmt/solver/runner/IncrementalApiTest.kt
ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3Model.kt
ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3Solver.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/BitVecTest.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/Example.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/FloatingPointTest.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/IncrementalApiTest.kt

Move utility extension functions from `KContext`
Pros:
Better usage when `with(ctx)` construction us not suitable (e.g. properties initialization):
```kotlin
class C (val ctx: KContext){
val a by ctx.intSort
val b = ctx.intSort.mkConst("b")
}
```
Cons:
Explicit imports are required:
```kotlin
import org.ksmt.utils.getValue // to allow by syntax
import org.ksmt.utils.mkConst
```

Better const creation API

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt
ksmt-core/src/main/kotlin/org/ksmt/KContext.kt
ksmt-core/src/main/kotlin/org/ksmt/cache/Cache.kt
ksmt-core/src/main/kotlin/org/ksmt/decl/KBitVecExprsDecl.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Arith.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Array.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Bool.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Integer.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KApp.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KBitVecExprs.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KExpr.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KFloatingPointExpr.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KFpRoundingMode.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KQuantifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Real.kt
ksmt-core/src/test/kotlin/org/ksmt/ExpressionSortTest.kt
ksmt-runner/src/main/kotlin/org/ksmt/runner/serializer/AstSerializer.kt
ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3ExprInternalizer.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/BitVecTest.kt

Currently, we have two ways to compute the sort of an expression: the `.expr` extension property, defined inside the `KContext` and `KExpr.sort()` method. It is unclear, which one to use.
From now on, we have the `KExpr.sort` property and the `.sort()` is deprecated.
Same with `.decl` and `.decl()`.
1. Remove the expr declaration cache, since a declaration can always be constructed in a constant time.
2. Don't cache sorts for expressions whose sort can be obtained in a constant time.
3. Don't use recursion to compute sort of deeply nested expressions (e.g. array store) to avoid `StackOverflow`.

Expr sort and decl API rework

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Array.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KApp.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KExpr.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KQuantifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/printer/ExpressionPrinter.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/printer/ExpressionPrinterWithLetBindings.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KBvExprSimplifier.kt

1. Don't use recursion during expression printing to avoid StackOverflow. 
2. Use let bindings (as in SMT-LIB) for shared subexpressions to minimize the resulting string.
Example:
```
(let (
(e!1 (select c_#memory_int c_~#ln2LO_exp~0.base))
(e!2 (concat (select e!1 (bvadd c_~#ln2LO_exp~0.offset #b00000000000000000000000000000100)) (select e!1 c_~#ln2LO_exp~0.offset)))
)
(eq c___ieee754_exp_~lo~0_primed (fp.mul c_currentRoundingMode c___ieee754_exp_~t~0_primed (fp.to_fp (extract (_ 63 63) e!2) (extract (_ 62 52) e!2) (extract (_ 51 0) e!2)))))
```

Expression printer

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprInternalizer.kt
ksmt-core/build.gradle.kts
ksmt-core/src/main/kotlin/org/ksmt/KContext.kt
ksmt-core/src/main/kotlin/org/ksmt/decl/KBitVecExprsDecl.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KBitVecExprs.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/KFloatingPointExpr.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KBvExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KFpExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/utils/BvUtils.kt
ksmt-core/src/main/kotlin/org/ksmt/utils/Utils.kt
ksmt-core/src/test/kotlin/org/ksmt/BvEvalTest.kt
ksmt-runner/src/main/kotlin/org/ksmt/runner/serializer/AstDeserializer.kt
ksmt-runner/src/main/kotlin/org/ksmt/runner/serializer/AstSerializer.kt
ksmt-runner/src/main/kotlin/org/ksmt/runner/serializer/SerializerUtils.kt
ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3ExprInternalizer.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/BitVecTest.kt
ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/FloatingPointTest.kt

Use BigInteger for custom sized Bv representation. 
This representation allows us to speed up various KSMT operations and results in a 2x performance gain on expression creation benchmark.

Bv and fp optimization

---

ksmt-core/src/main/kotlin/org/ksmt/KContext.kt

Change visibility modifiers of methods responsible for cache creation inside `KContext` from `private` to `protected`. This should allow users to implement caches in inheritors of `KContext` more smoothly.

Make functions for cache creation protected

---

ksmt-core/src/main/kotlin/org/ksmt/utils/NativeLibraryLoader.kt
ksmt-z3/build.gradle.kts

Download required Z3 libraries from the releases for computers with macOS on Apple Silicon processors.
Updated Z3 version from `4.11.2` to `4.12.1`

Add support for macOS with aarch64

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprInternalizer.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaInternalizationAxioms.kt
ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/SolverTest.kt

Better support for array lambda expressions in bitwuzla. Produce quantifiers for array eq/distinct expressions only.

Bitwuzla array lambdas

---

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaContext.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprInternalizer.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaModel.kt
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaSolver.kt
ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/ConverterTest.kt
ksmt-test/src/main/kotlin/org/ksmt/test/TestWorkerProcess.kt

Avoid full expression cache copying on each push. Store at most 2 x number of internalized expressions.

Bitwuzla ctx improvement

---

README.md
buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-z3/build.gradle.kts

Downgrade `Z3` version in order to support OS with max `glibc` version of `2.31`

Downgrade z3 version

---

README.md
buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-core/src/main/kotlin/org/ksmt/KContext.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/BoolSimplification.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrdering.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KArithExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KArrayExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KBoolExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KBvExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KFpExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/transformer/KNonRecursiveTransformer.kt
ksmt-core/src/test/kotlin/org/ksmt/SimplifierTest.kt
ksmt-test/src/test/kotlin/org/ksmt/test/MultiIndexedArrayTest.kt

Redorder arguments of expressions like `and` or `eq` to ensure that `(and a b c)` and `(and b c a)` are the same expression. This transformation allows us to improve expression interning cache hit rate.

Expression arguments ordering

---

ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrdering.kt
ksmt-core/src/test/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrderingTest.kt

The following exception happened: 
```
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
at java.base/java.util.TimSort.sort(TimSort.java:245)
at java.base/java.util.Arrays.sort(Arrays.java:1515)
at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
at java.base/java.util.Collections.sort(Collections.java:179)
at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
at org.ksmt.expr.rewrite.simplify.ExpressionOrderingKt.ensureExpressionsOrder(ExpressionOrdering.kt:40)
at …
```

Expression ordering made TimSort fail

---

buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts
ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaModel.kt
ksmt-core/build.gradle.kts
ksmt-core/src/main/kotlin/org/ksmt/KContext.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/Array.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/ArithSimplification.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/ArraySimplification.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KArrayExprSimplifier.kt
ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KExprSimplifierBase.kt
ksmt-core/src/main/kotlin/org/ksmt/solver/model/KModelEvaluator.kt
ksmt-core/src/main/kotlin/org/ksmt/solver/model/KModelImpl.kt
ksmt-core/src/main/kotlin/org/ksmt/utils/ArithUtils.kt
ksmt-core/src/test/kotlin/org/ksmt/ArraySimplifyTest.kt
ksmt-core/src/test/kotlin/org/ksmt/ExpressionSimplifyTest.kt
ksmt-yices/src/main/kotlin/org/ksmt/solver/yices/KYicesModel.kt

Keep information about interpreted array store indices to achieve constant lookups during array select simplification.
* Use `array store` indices information in simplifiers.
* Use similar approach with `interpreted values` analysis in `KModelEvaluator` to speedup function interpreteation argument lookups.
* Array simplification tests. 
* Fix array indices inequality checks. For now, we treat indices as distinct if ANY index is distinct.
* Fix bug with integer mod evaluation in case of negative modulus.
Array store memory usage analysis with different indices patterns.
We consider arrays with an `int` indices and `int` values (as in `ArraySimplifyTest`).
Memory usage includes all memory used by `array store`, it indices, value, caches and all memory used by the `KContext`, to store all …

Faster array select simplification

---

ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3Context.kt

Remove `decRef` "optimization" since it results in a great performace degradation on some benchmark instances. For example, `close` without `decRef` takes about 1 minute and with `decRef` `close` completes in a few milliseconds.

Z3: fix dec ref on close

---

README.md
docs/advanced-usage.md
docs/getting-started.md
examples/build.gradle.kts
examples/src/main/kotlin/AdvancedExamples.kt

Extend readme with an overview section and provide more detailed documentation on advanced features.

Documentation update

---

ksmt-bitwuzla/src/main/kotlin/io/ksmt/solver/bitwuzla/KBitwuzlaContext.kt
ksmt-cvc5/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5Context.kt
ksmt-test/src/test/kotlin/io/ksmt/test/CheckWithAssumptionsTest.kt
ksmt-z3/src/main/kotlin/io/ksmt/solver/z3/KZ3Context.kt
ksmt-z3/src/main/kotlin/io/ksmt/solver/z3/KZ3Solver.kt

* Fix solver close. Don't close when the solver is already closed.
* Fix trivial unsat core handling in Z3 (#112).

Fix unsat core generation

---

ksmt-z3/src/main/kotlin/io/ksmt/solver/z3/KZ3Context.kt

Added missing decRefs on `uninterpretedSortValueDecls`, `uninterpretedSortValueInterpreters`, `converterNativeObjects`.
Without this, native context closing sometimes lasted forever.

Z3 decRefs on context close fix

---

ksmt-z3/src/main/kotlin/io/ksmt/solver/z3/KZ3ExprConverter.kt

Support `idiv` and `bvcomp` operations in Z3 converter

Z3: add conversion for `idiv` and `bvcomp` operations

---

README.md
buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-core/src/main/kotlin/io/ksmt/solver/model/KModelImpl.kt
ksmt-symfpu/build.gradle.kts
ksmt-symfpu/src/main/kotlin/io/ksmt/symfpu/solver/KSymFpuModel.kt
ksmt-symfpu/src/main/kotlin/io/ksmt/symfpu/solver/KSymFpuSolver.kt
ksmt-symfpu/src/test/kotlin/io/ksmt/symfpu/ArraySymFpuTest.kt
ksmt-symfpu/src/test/kotlin/io/ksmt/symfpu/ModelTest.kt
ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/FpBenchmarks.kt
ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/SymFpuBenchmarksBasedTest.kt

Fix `function-as-array` handling in SymFpu model

Symfpu model fix

---

README.md
buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-z3/ksmt-z3-core/build.gradle.kts
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3ExprConverter.kt
ksmt-z3/ksmt-z3-native/build.gradle.kts

- Upgrade Z3 version to 4.12.2
- Use custom prebuilt linux binary with fewer runtime dependencies

Upgrade Z3 version to 4.12.2

---

README.md
buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/ArithSimplificationRules.kt
ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/KExprSimplifier.kt
ksmt-symfpu/src/main/kotlin/io/ksmt/symfpu/solver/FpToBvTransformer.kt
ksmt-test/src/test/kotlin/io/ksmt/test/ModelGenerationTest.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3ExprConverter.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3Model.kt

Z3: Fix model detach

---

README.md
buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-bitwuzla/ksmt-bitwuzla-core/src/main/kotlin/io/ksmt/solver/bitwuzla/KBitwuzlaModel.kt
ksmt-bitwuzla/ksmt-bitwuzla-core/src/main/kotlin/io/ksmt/solver/bitwuzla/KBitwuzlaSolver.kt
ksmt-bitwuzla/ksmt-bitwuzla-core/src/test/kotlin/io/ksmt/solver/bitwuzla/Example.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/KModel.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/model/KModelImpl.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/model/KNativeSolverModel.kt
ksmt-cvc5/ksmt-cvc5-core/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5Model.kt
ksmt-cvc5/ksmt-cvc5-core/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5Solver.kt
ksmt-symfpu/src/main/kotlin/io/ksmt/symfpu/solver/KSymFpuModel.kt
ksmt-symfpu/src/test/kotlin/io/ksmt/symfpu/ModelTest.kt
ksmt-yices/ksmt-yices-core/src/main/kotlin/io/ksmt/solver/yices/KYicesModel.kt
ksmt-yices/ksmt-yices-core/src/main/kotlin/io/ksmt/solver/yices/KYicesSolver.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3Model.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3Solver.kt
ksmt-z3/ksmt-z3-core/src/test/kotlin/io/ksmt/solver/z3/Example.kt

Release native model on `KModel.detach`
Test run: https://github.com/UnitTestBot/ksmt/actions/runs/7731232884

Rework model detach

---

README.md
buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts
docs/getting-started.md
examples/build.gradle.kts
ksmt-bitwuzla/ksmt-bitwuzla-core/src/main/kotlin/io/ksmt/solver/bitwuzla/KBitwuzlaSolverConfiguration.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/KSolverConfiguration.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/KSolverUniversalConfigurationBuilder.kt
ksmt-core/src/main/kotlin/io/ksmt/solver/KTheory.kt
ksmt-core/src/main/kotlin/io/ksmt/utils/KExprTheoryRequirement.kt
ksmt-cvc5/ksmt-cvc5-core/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5Solver.kt
ksmt-cvc5/ksmt-cvc5-core/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5SolverConfiguration.kt
ksmt-cvc5/ksmt-cvc5-core/src/test/kotlin/io/ksmt/solver/cvc5/LogicTest.kt
ksmt-runner/src/main/kotlin/io/ksmt/runner/generated/models/SolverProtocolModel.Generated.kt
ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverRunner.kt
ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverRunnerExecutor.kt
ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverRunnerUniversalConfigurator.kt
ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverState.kt
ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverWorkerProcess.kt
ksmt-runner/src/main/rdgen/io/ksmt/runner/models/SolverProtocolModel.kt
ksmt-runner/src/test/kotlin/io/ksmt/solver/runner/CustomSolverTest.kt
ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/BenchmarksBasedTest.kt
ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/Cvc5BenchmarksBasedTest.kt
ksmt-yices/ksmt-yices-core/src/main/kotlin/io/ksmt/solver/yices/KYicesSolver.kt
ksmt-yices/ksmt-yices-core/src/main/kotlin/io/ksmt/solver/yices/KYicesSolverConfiguration.kt
ksmt-yices/ksmt-yices-core/src/test/kotlin/io/ksmt/solver/yices/LogicTest.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3Solver.kt
ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3SolverConfiguration.kt
ksmt-z3/ksmt-z3-core/src/test/kotlin/io/ksmt/solver/z3/LogicTest.kt

Add option to configure solver to work with specific theories

Theories specialization
