ksmt-core/build.gradle.kts, ksmt-core/src/main/kotlin/org/ksmt/solver/KSolver.kt
=> Fix java compatibility issues

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaContext.kt, ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt, ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprInternalizer.kt, ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/bindings/Native.kt, ksmt-core/src/main/kotlin/org/ksmt/expr/KFloatingPointExpr.kt, ksmt-test/src/test/kotlin/org/ksmt/test/BitwuzlaBenchmarksBasedTest.kt
Implement Fp operations in Bitwuzla converter/internalizer
=> Support FP in Bitwuzla

README.md
Highlight KSMT key features in readme.
=> KSMT key features.

docs/getting-started.md, ksmt-core/src/main/kotlin/org/ksmt/parser/KSMTLibParseException.kt, ksmt-core/src/main/kotlin/org/ksmt/parser/KSMTLibParser.kt, ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3SMTLibParser.kt, ksmt-z3/src/test/kotlin/org/ksmt/solver/z3/ParserTest.kt
=> Parser API

ksmt-core/src/main/kotlin/org/ksmt/utils/ContextUtils.kt
Expression cast utility as discussed in #40
=> Expression checked cast utility

COPYRIGHT_HEADER.txt, LICENSE, NOTICE
LICENSE, NOTICE and COPYRIGHT_HEADER.txt were added according to the rules for applying the Apache License 2.0:
https://apache.org/foundation/license-faq.html#Apply-My-Software
https://choosealicense.com/licenses/apache-2.0/
=> License information added

ksmt-z3/src/main/kotlin/org/ksmt/solver/z3/KZ3ExprConverter.kt
Suuport conversion of array lambda expression in Z3 (missed todo).
=> Z3 array lambda converter

README.md, Requirements.md, buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts, docs/custom-expressions.md, docs/getting-started.md, examples/build.gradle.kts, examples/src/main/kotlin/CustomExpressions.kt
Guide on how to extend KSMT with custom expressions as requested in #70
=> Custom expression documentation

ksmt-core/src/main/kotlin/org/ksmt/expr/rewrite/simplify/KExprSimplifier.kt, ksmt-core/src/main/kotlin/org/ksmt/expr/transformer/KNonRecursiveTransformerBase.kt
Extend transformer with an option to skip the transformation of some expressions.
=> Expression transformation skip

docs/custom-expressions.md, examples/src/main/kotlin/CustomExpressions.kt
Actualize examples wrt recent changes in the solver API.
=> Actualize examples

README.md, buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts
Upgrade version from 0.4.2 to 0.4.3 everywhere.
=> Upgrade version to 0.4.3

README.md, buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-bitwuzla/dist/build.md, ksmt-cvc5/dist/build.md, ksmt-yices/dist/build.md
* Add MacOS aarch64 platform into the list of supported platforms.
* Add some build instructions/notes for native libraries.
=> Documentation update

README.md, buildSrc/src/main/kotlin/org.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, examples/src/main/kotlin/CustomExpressions.kt, ksmt-core/src/main/kotlin/org/ksmt/KContext.kt, ksmt-core/src/main/kotlin/org/ksmt/expr/transformer/KNonRecursiveTransformerBase.kt, ksmt-core/src/test/kotlin/org/ksmt/NestedTransformationTest.kt
Allow nested transformer `apply` invocations.
=> Nested transformers

ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaExprConverter.kt, ksmt-bitwuzla/src/main/kotlin/org/ksmt/solver/bitwuzla/KBitwuzlaModel.kt, ksmt-bitwuzla/src/test/kotlin/org/ksmt/solver/bitwuzla/SolverTest.kt
* Fix array model retrieval for muliindexed arrays
* Recognize array store pattern to avoid lambda expressions in model
=> Fix array model conversion

ksmt-yices/src/main/kotlin/org/ksmt/solver/yices/KYicesSolver.kt
Fix timer thread was not stopped on Yices solver close.
=> Yices: stop timer on solver close

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-bitwuzla/src/main/kotlin/io/ksmt/solver/bitwuzla/KBitwuzlaExprInternalizer.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/ArithSimplification.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/BvSimplification.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/FpSimplification.kt, ksmt-core/src/main/kotlin/io/ksmt/solver/util/KExprInternalizerUtils.kt, ksmt-core/src/main/kotlin/io/ksmt/utils/ArithUtils.kt, ksmt-core/src/main/kotlin/io/ksmt/utils/FpUtils.kt, ksmt-core/src/test/kotlin/io/ksmt/ArithSimplifyTest.kt, ksmt-core/src/test/kotlin/io/ksmt/BvSimplifyTest.kt, ksmt-core/src/test/kotlin/io/ksmt/FpEvalTest.kt, ksmt-cvc5/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5ExprInternalizer.kt, ksmt-test/src/main/kotlin/io/ksmt/test/RandomExpressionGenerator.kt, ksmt-test/src/test/kotlin/io/ksmt/test/ContextAstInterningTest.kt, ksmt-test/src/test/kotlin/io/ksmt/test/TestBvOverflowChecks.kt, ksmt-yices/src/main/kotlin/io/ksmt/solver/yices/KYicesContext.kt, ksmt-yices/src/main/kotlin/io/ksmt/solver/yices/KYicesExprInternalizer.kt
* Support overflow check expressions in all solvers by  rewriting with other Bv expressions
* Fix overflow check expressions in Bitwuzla
* Add tests
* Bitwuzla: better handling of single dimension constant arrays
* Yices: allow negative indices for uninterpreted sort values
* Core: arithmetic power operation evaluator 
* Core: fp.rem operation evaluator
* Core: fp.fma operation evaluator
=> Various improvements

README.md, docs/advanced-usage.md, docs/custom-expressions.md, docs/getting-started.md
Reviewed `Readme.md` and `/docs` for linguistic and formatting issues.
Note: docs should look nice for both GitHub and website.
=> Reviewed Readme and /docs

ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/ArithSimplification.kt, ksmt-core/src/main/kotlin/io/ksmt/utils/ArithUtils.kt, ksmt-core/src/test/kotlin/io/ksmt/ArithSimplifyTest.kt
Fix: integer mod/rem operations simplification doesn't match theory rules and solvers interpretation.
=> Fix integer mod/rem simplification

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-core/src/main/kotlin/io/ksmt/KContext.kt
Document all expression builders in  `KContext`
=> KContext docs

ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/ArithSimplificationRules.kt, ksmt-core/src/test/kotlin/io/ksmt/ArithSimplifyTest.kt, ksmt-cvc5/src/main/kotlin/io/ksmt/solver/cvc5/KCvc5ExprInternalizer.kt
* Fix integer division in cvc5
* Fix integer division eval
=> Fix int division

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KNonRecursiveTransformerBase.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KNonRecursiveVisitor.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KNonRecursiveVisitorBase.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KVisitor.kt, ksmt-core/src/test/kotlin/io/ksmt/ExpressionVisitorTest.kt
* KVisitor for the KExpr
* Non recursive KVisitor implementation
=> Expression visitor

.github/workflows/release.yml, ksmt-symfpu/build.gradle.kts
Fix release configuration for the `ksmt-symfpu` module
=> Update SymFpu release config

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-runner/src/main/kotlin/io/ksmt/solver/portfolio/KPortfolioSolver.kt
=> Terminate solver on close

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-core/src/main/kotlin/io/ksmt/expr/rewrite/simplify/KBoolExprSimplifier.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KNonRecursiveTransformerBase.kt, ksmt-core/src/main/kotlin/io/ksmt/expr/transformer/KNonRecursiveVisitorBase.kt, ksmt-core/src/main/kotlin/io/ksmt/solver/KSolver.kt, ksmt-runner/src/main/kotlin/io/ksmt/runner/generated/models/SolverProtocolModel.Generated.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/async/KAsyncSolver.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/portfolio/KPortfolioSolver.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverRunner.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverRunnerExecutor.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverState.kt, ksmt-runner/src/main/kotlin/io/ksmt/solver/runner/KSolverWorkerProcess.kt, ksmt-runner/src/main/rdgen/io/ksmt/runner/models/SolverProtocolModel.kt, ksmt-runner/src/test/kotlin/io/ksmt/solver/runner/SolverRunnerTest.kt
=> Bulk assert solver API

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-bitwuzla/ksmt-bitwuzla-native/build.gradle.kts, ksmt-cvc5/ksmt-cvc5-native/build.gradle.kts, ksmt-yices/ksmt-yices-native/build.gradle.kts, ksmt-z3/ksmt-z3-native/build.gradle.kts
=> Fix release builds

README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3ExprConverter.kt, ksmt-z3/ksmt-z3-core/src/test/kotlin/io/ksmt/solver/z3/FloatingPointTest.kt
=> Z3: support `fp.to_ieee_bv` internal decl

.github/workflows/build-and-run-tests.yml, .github/workflows/release.yml, .github/workflows/run-long-tests.yml, README.md, buildSrc/src/main/kotlin/io.ksmt.ksmt-base.gradle.kts, docs/getting-started.md, examples/build.gradle.kts, ksmt-core/src/main/kotlin/io/ksmt/utils/FpUtils.kt, ksmt-core/src/test/kotlin/io/ksmt/ExpressionEvalTest.kt, ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/BenchmarksBasedTest.kt, ksmt-test/src/test/kotlin/io/ksmt/test/benchmarks/Z3BenchmarksBasedTest.kt, ksmt-z3/ksmt-z3-core/build.gradle.kts, ksmt-z3/ksmt-z3-core/src/main/kotlin/io/ksmt/solver/z3/KZ3ExprConverter.kt, ksmt-z3/ksmt-z3-native/build.gradle.kts
- Upgrade Z3 to 4.12.5
- Fix fma in FpUtils
- Enable more fp tests
- Upgrade github actions
Tests:
- https://github.com/UnitTestBot/ksmt/actions/runs/7703467954
- https://github.com/UnitTestBot/ksmt/actions/runs/7707936011
=> Upgrade z3 version to 4.12.5
